runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.main.app

- url: /\d+
  script: main.displayprime.app

- url: /view
  script: main.displayprime.app

- url: /admin(/)?
  static_files: admin/admin.html
  upload: admin/admin.html
  secure: always
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- appstats: on
