runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.main.app
  secure: always

- url: /\d+
  script: main.displayprime.app
  secure: always

- url: /view
  script: main.displayprime.app
  secure: always

- url: /admin(/)?
  script: admin.admin.app
  secure: always
  login: admin

- url: /admin/verifycalculation
  script: admin.admin.app
  secure: always
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- appstats: on
